const List<String> bniBusinessCategories = [
  "Accounting",
  "Advertising & Marketing",
  "Agriculture",
  "Apparel & Accessories",
  "Architecture",
  "Art & Photography",
  "Automotive",
  "Banking",
  "Beauty & Spa",
  "Business Consulting",
  "Catering",
  "Child Care",
  "Cleaning Services",
  "Computer Services",
  "Construction",
  "Design",
  "Education",
  "Employment Services",
  "Entertainment",
  "Event Planning",
  "Financial Services",
  "Fitness",
  "Florist",
  "Food & Beverage",
  "Funeral Services",
  "Furniture",
  "Graphic Design",
  "Health & Wellness",
  "Home Maintenance",
  "Hospitality",
  "Insurance",
  "Interior Design",
  "IT Services",
  "Jewelry",
  "Landscaping",
  "Legal Services",
  "Logistics",
  "Manufacturing",
  "Media Production",
  "Medical Services",
  "Mortgage",
  "Moving Services",
  "Non-Profit",
  "Pest Control",
  "Pet Services",
  "Plumbing",
  "Printing",
  "Public Relations",
  "Real Estate - Commercial",
  "Real Estate - Residential",
  "Renewable Energy",
  "Retail",
  "Security",
  "Software Development",
  "Telecommunications",
  "Travel",
  "Web Development",
  "Wholesale",
  "Other"
];
