/// BNI Guntur (BNIG) business categories for member registration.
///
/// The single field the matching engine seats people by — no two members of
/// the same category share a table. Sourced from the official BNIG category
/// list (updated 2026-09). Keep entries unique and human-readable.
const List<String> bniBusinessCategories = [
  "Ad Agency",
  "Advertising",
  "Advocate",
  "Agricultural Implants",
  "Architecture",
  "Artist",
  "Automation, Audio & Video",
  "Bakery",
  "Bank E-Auction",
  "Banking",
  "Blood Bank",
  "Borewells",
  "Boutique",
  "Builder",
  "Business Consultant",
  "CA",
  "Cams Sales and Service",
  "Car Detailing &  Accessories",
  "Catering",
  "CCTV",
  "Chits & Finance",
  "Civil / Structural Engineer",
  "Civil Work contractor",
  "Commercial Loans",
  "Computers",
  "Crackers",
  "Credit Card Management",
  "Critical Care Physician",
  "D & C Air conditioning",
  "Dairy Farms",
  "Dentist",
  "Dermatologist",
  "Diagnostics",
  "Digital Marketing",
  "Education",
  "Electrical",
  "Electrical Contractor",
  "Elevator",
  "Energy Consulting",
  "ENT",
  "Events",
  "Fabric & Textile",
  "Fabrication",
  "Financial Consultant",
  "Fire Safety",
  "Forex Dealer",
  "Furniture",
  "General Insurance",
  "General Medicine",
  "General Physician",
  "Gifts",
  "Glass",
  "Gold",
  "Gold Imitation",
  "GPS Tracking Services",
  "Granite",
  "Grocery",
  "Gypsum Plastering",
  "Hair Stylist",
  "Hardware",
  "Health & wellness",
  "Health Care",
  "Health Insurance",
  "Home Appliances",
  "Home Foods",
  "Home Furnishing",
  "Home Loans",
  "Home theater & Sound System",
  "Human Resource",
  "Interiors",
  "Industrial scrap and Recycling",
  "Iron & Steel",
  "Iron & Steel Fabrication",
  "Iron Products Manufacturing",
  "Kids Toys",
  "LED Manufacturer",
  "Life Insurance",
  "Manufacturing",
  "Medical Consultancy",
  "Mobile & Accessories",
  "Mobile App",
  "Modular Cabinets Manufacture",
  "Modular Cupboards",
  "Modular Kitchen",
  "Mutual Funds",
  "Neurologist",
  "NGO",
  "Oncologist",
  "Open Lands",
  "Open Plots",
  "Ophthalmologist",
  "Orthopaedic",
  "Overseas",
  "Paints",
  "Party Space",
  "Pediatrician",
  "Pest Control",
  "Pharma Marketing",
  "Pharmaceutical Distribution",
  "Pharmacist",
  "Photography",
  "Physiotherapist",
  "Plywood",
  "Printing",
  "Pulmonologist",
  "Purohith",
  "PVC Pipes",
  "Real Estate",
  "Red Sandal Wood Farm Lands",
  "Restaurant",
  "Restaurant Consultant",
  "Robotics",
  "Salon",
  "Sanitaryware",
  "Security Services",
  "Silver",
  "Social Media",
  "Software Development",
  "Solar",
  "Stone Manufacturing",
  "Sweets",
  "Tally Software",
  "Tax Advisory",
  "Tiles",
  "Tiles Manufacturing",
  "Tours & Travels",
  "Trainings",
  "Tuitions",
  "UPVC Windows and Doors",
  "Used Cars Sales",
  "Vasthu",
  "Vetenirary",
  "Water Purifier",
  "Womans Apparel",
  "Wood Work",
  "Other",
];
